# Generated by Django 4.0.3 on 2022-07-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_remove_accountvo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
